services:
  pct-producer:
    build:
      context: .
      dockerfile: deploy/Dockerfile-producer
    ports:
      - "8080:8080"
  postgres:
    image: postgres:16.6
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=pct
    ports:
      - "5432:5432"  # PostgreSQL의 기본 포트 매핑
    volumes:
      - pg-data:/var/lib/postgresql/data  # 데이터를 호스트와 공유

  broker-1:
    image: confluentinc/cp-kafka:7.7.1
    hostname: broker-1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      #      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093, 2@broker-2:29093, 3@broker-3:29093'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker-1:29092,CONTROLLER://broker-1:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  #  broker-2:
  #    image: confluentinc/cp-kafka:7.7.1
  #    hostname: broker-2
  #    ports:
  #      - "9093:9092"
  #    environment:
  #      KAFKA_NODE_ID: 2
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:29092,PLAINTEXT_HOST://localhost:9092'
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #      KAFKA_PROCESS_ROLES: 'broker,controller'
  #      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093, 2@broker-2:29093, 3@broker-3:29093'
  #      KAFKA_LISTENERS: 'PLAINTEXT://broker-2:29092,CONTROLLER://broker-2:29093,PLAINTEXT_HOST://0.0.0.0:9092'
  #      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  #      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
  #
  #  broker-3:
  #    image: confluentinc/cp-kafka:7.7.1
  #    hostname: broker-3
  #    ports:
  #      - "9094:9092"
  #    environment:
  #      KAFKA_NODE_ID: 3
  #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
  #      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-3:29092,PLAINTEXT_HOST://localhost:9092'
  #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  #      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
  #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  #      KAFKA_PROCESS_ROLES: 'broker,controller'
  #      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker-1:29093, 2@broker-2:29093, 3@broker-3:29093'
  #      KAFKA_LISTENERS: 'PLAINTEXT://broker-3:29092,CONTROLLER://broker-3:29093,PLAINTEXT_HOST://0.0.0.0:9092'
  #      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
  #      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
  #      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
  #      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.7.1
    hostname: schema-registry
    depends_on:
      - broker-1
    #      - broker-2
    #      - broker-3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-1:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8084:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker-1:29092
    depends_on:
      - broker-1
#      - broker-2
#      - broker-3

volumes:
  pg-data:  # PostgreSQL 데이터를 저장할 볼륨 정의
