receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  # 필요시 아래 regex processor를 활성화하여 로그 본문에서 jobId를 추출할 수 있습니다.
  # regex:
  #   logs:
  #     - name: extract_jobId
  #       pattern: '.*jobId=(?P<jobId>[a-zA-Z0-9_-]+).*'
  #       parse_from: body

  attributes:
    actions:
      - key: jobId
        action: insert
        value: "default_jobId"

exporters:
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    static_labels:
      service: "pct-producer-1"
    structured_metadata_keys: ["jobId"]

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [loki]
