FROM openjdk:21-jdk-slim
LABEL authors="gunbos"

ADD producer/build/libs/pct-producer.jar /app.jar
ENV OTEL_AGENT_VERSION="2.13.0"
ADD "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v${OTEL_AGENT_VERSION}/opentelemetry-javaagent.jar" "/opentelemetry-javaagent.jar"

ENTRYPOINT java -javaagent:/opentelemetry-javaagent.jar \
      -Dotel.traces.exporter=logging \
      -Dotel.metrics.exporter=logging \
      -Dotel.logs.exporter=logging \
      -jar /app.jar
