### Get
GET http://localhost:8080

### Get Log
http://localhost:8082/logs?query=



### Post Produce
POST http://localhost:8080
Content-Type: application/json

{
  "partitionName": "pctJob"
}

### Alter Partition
POST http://localhost:8080/alter-partition-count
Content-Type: application/json

{
  "count": 3,
  "partitionName": "parallel-pctJob"
}
